### ISSUE TITLE
Multibranch with spaces in repo path fails

### ISSUE THREAD

**Issue by pollockm** [p4paul/p4-jenkins#38]
Using multibranch pipeline with Helix branches with no spaces in path succeeds both scanning and building:
//repo/project/*

Using multibranch pipeline with Helix branches with spaces in path scans repo and finds Jenkinsfile, but fails build with invalid client view
//repo/project with spaces/*

Using multibranch pipeline with Helix branches with spaces in path with double quotes fails to scan repo with error text below:
"//repo/project with spaces/*"

ERROR: [Mon Jul 16 17:40:22 CDT 2018] Could not fetch branches from source 77c0ab9e-896d-4de3-b455-285738e171e9
java.io.IOException: P4JAVA: Error(s):
"//repo/project with spaces/*"/*/... - must create client '_____CLIENT_UNSET_____' to access local files.

	at org.jenkinsci.plugins.p4.scm.AbstractP4ScmSource.retrieve(AbstractP4ScmSource.java:172)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:357)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:267)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:633)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1024)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
[Mon Jul 16 17:40:22 CDT 2018] Finished branch indexing. Indexing took 35 ms
FATAL: Failed to recompute children of sts
java.io.IOException: P4JAVA: Error(s):
"//repo/project with spaces"/*/... - must create client '_____CLIENT_UNSET_____' to access local files.

	at org.jenkinsci.plugins.p4.scm.AbstractP4ScmSource.retrieve(AbstractP4ScmSource.java:172)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:357)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:267)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:633)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1024)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE

**Comment by p4paul** [comment]
Sorry for the delay in my reply I have been held up on a few projects. Thank you for raising the issues, but please can you use Jenkins JIRA: 
issues.jenkins-ci.org
Alternatively if you have support with Perforce, please open a ticket and inform them of the JIRA issue.
Kind regards,
Paul

**Comment by pollockm** [comment]
Will do - apologies for the incorrect reporting.

**Comment by p4paul** [comment]
No problem - thank you for taking the time to report both issues.  If at any point you want to create a Git Pull Request please use https://github.com/jenkinsci/p4-plugin and not this fork.
I will close both issues for you when you have the JIRA issues.

**Comment by p4paul** [comment]
Closing Issue; moved to: https://github.com/p4paul/p4-jenkins/issues/38
